### ISSUE TITLE
Error when running the playbook

### ISSUE THREAD

**Issue by ewchuah** [clay584/genie_collection#4]
i cloned the repo and followed the steps in the readme.md file. But receive the following errors.  Am i missing anything?

`(venv_toolkit_py36) [chuahew@dev-centos genie_collection]$ ansible-playbook -i inventory test.yml

PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Learn Genie - 1st Run] **************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/home/chuahew/environments/venv_toolkit_py36/lib64/python3.6/site-packages/genie/libs/ops/ops.json'
fatal: [sbx-nxos-mgmt.cisco.com]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/chuahew/.ansible/tmp/ansible-tmp-1591716580.0907028-127361165296680/AnsiballZ_learn_genie.py", line 102, in <module>
        _ansiballz_main()
      File "/home/chuahew/.ansible/tmp/ansible-tmp-1591716580.0907028-127361165296680/AnsiballZ_learn_genie.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/chuahew/.ansible/tmp/ansible-tmp-1591716580.0907028-127361165296680/AnsiballZ_learn_genie.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.learn_genie', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_learn_genie_payload_bnxmry2p/ansible_learn_genie_payload.zip/ansible/modules/lea ignored=0 ``

**Comment by ewchuah** [comment]
managed to get it working... you can close ths issue.. 

> i cloned the repo and followed the steps in the readme.md file. But receive the following errors. Am i missing anything?
> 
> `(venv_toolkit_py36) [chuahew@dev-centos genie_collection]$ ansible-playbook -i inventory test.yml
> 
> PLAY [all] ********************************************************************************************************************************************************************************************************
> 
> TASK [Learn Genie - 1st Run] **************************************************************************************************************************************************************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/home/chuahew/environments/venv_toolkit_py36/lib64/python3.6/site-packages/genie/libs/ops/ops.json'
> fatal: [sbx-nxos-mgmt.cisco.com]: FAILED! => changed=false
> module_stderr: |-
> Traceback (most recent call last):
> File "/home/chuahew/.ansible/tmp/ansible-tmp-1591716580.0907028-127361165296680/AnsiballZ_learn_genie.py", line 102, in
> _ansiballz_main()
> File "/home/chuahew/.ansible/tmp/ansible-tmp-1591716580.0907028-127361165296680/AnsiballZ_learn_genie.py", line 94, in _ansiballz_main
> invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
> File "/home/chuahew/.ansible/tmp/ansible-tmp-1591716580.0907028-127361165296680/AnsiballZ_learn_genie.py", line 40, in invoke_module
> runpy.run_module(mod_name='ansible.modules.learn_genie', init_globals=None, run_name='**main**', alter_sys=True)
> File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
> return _run_module_code(code, init_globals, run_name, mod_spec)
> File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/tmp/ansible_learn_genie_payload_bnxmry2p/ansible_learn_genie_payload.zip/ansible/modules/lea ignored=0 ``
