### ISSUE TITLE
Pyats.utils.exception : Missing keys when a test playbook ran against sbx

### ISSUE THREAD

**Issue by bronitskiy** [clay584/genie_collection#6]
Having issues running a test playbook (with genie learn arp module) and the following exception returned:
```
 pyats.utils.exceptions.SchemaMissingKeyError: Missing keys:
      "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
      "type"  parent: [devices.sbx-nxos-mgmt.cisco.com]
```

The full output can be found below:
```
(.venv) [root@292c4c38a3f8 genie_collection-master]# pwd
/genie_collection-master
(.venv) [root@292c4c38a3f8 genie_collection-master]# tree
.
|-- LICENSE
|-- NOTICE
|-- Pipfile
|-- Pipfile.lock
|-- README.md
|-- ansible.cfg
|-- clay584
|   `-- genie
|       |-- README.md
|       |-- clay584-genie-0.1.7.tar.gz
|       |-- colored_diff.png
|       |-- galaxy.yml
|       |-- learn_genie_params.png
|       `-- plugins
|           |-- filter
|           |   `-- parse_genie.py
|           `-- modules
|               |-- args.json
|               `-- learn_genie.py
|-- genie_filter_testing.yml
|-- inventory
|-- test.yml
|-- test_arp.yaml
-- yamllint_config.yml
5 directories, 19 files
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# cat test_arp.yaml
---
- hosts: all
  gather_facts: false
  connection: local
  collections:
   - clay584.genie
  tasks:
    - name: Learn Genie - ARP
      learn_genie:
        host: "{{ ansible_host }}"
        port: 8181
        protocol: ssh
        username: admin
        password: Admin_1234!
        os: nxos
        feature: arp
      register: genie_arp1
    - name: Debug Genie
      debug:
        msg: "{{ genie_arp1 }}"
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# ansible --version
ansible 2.10.6
  config file = /genie_collection-master/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/genie_collection-master/clay584/genie/plugins/modules']
  ansible python module location = /.venv/lib64/python3.6/site-packages/ansible
  executable location = /.venv/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# cat inventory
all:
  hosts:
    sbx-nxos-mgmt.cisco.com:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# ansible-playbook test_arp.yaml -i inventory -v
Using /genie_collection-master/ansible.cfg as config file

PLAY [all] ************************************************************************************************************************************************************

TASK [Learn Genie - ARP] **********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
fatal: [sbx-nxos-mgmt.cisco.com]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1615507860.465231-957-197841320397725/AnsiballZ_learn_genie.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1615507860.465231-957-197841320397725/AnsiballZ_learn_genie.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1615507860.465231-957-197841320397725/AnsiballZ_learn_genie.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.clay584.genie.plugins.modules.learn_genie', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_learn_genie_payload_s18eg0q9/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 367, in <module>
      File "/tmp/ansible_learn_genie_payload_s18eg0q9/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 363, in main
      File "/tmp/ansible_learn_genie_payload_s18eg0q9/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 296, in run_module
      File "src/genie/testbed.py", line 4, in genie.testbed.load
      File "src/genie/conf/main.py", line 81, in genie.conf.main.Genie.init
      File "/.venv/lib64/python3.6/site-packages/pyats/topology/loader/__init__.py", line 41, in load
        return TestbedFileLoader(**init_kwargs).load(loadable, **kwargs)
      File "src/pyats/utils/yaml/loader.py", line 134, in pyats.utils.yaml.loader.Loader.load
      File "src/pyats/utils/schemaengine.py", line 403, in pyats.utils.schemaengine.Schema.validate
    pyats.utils.exceptions.SchemaMissingKeyError: Missing keys:
      "type"  parent: [devices.sbx-nxos-mgmt.cisco.com]
      "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ************************************************************************************************************************************************************
sbx-nxos-mgmt.cisco.com    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by clay584** [comment]
This is a parser issue that needs to be addressed by the Cisco pyATS team. You can submit an issue here.

https://github.com/CiscoTestAutomation/genieparser/issues

**Comment by bronitskiy** [comment]
@clay584 pyATS team's reply was that the problem appears to be related to Genie's testbed "schema" ("devices" block in particular).
It appeared to them that my genie testbed file should have been missing those parameters ("type" and "connections") for a device it was connecting to.

This is the documentation link they provided, describing testbed file schema and required keys:
https://pubhub.devnetcloud.com/media/pyats/docs/topology/schema.html

From the link above, you see how both "type" and "connections" parameters marked as "(**required**") for the "device block" portion of the testbed file:
```
# devices block
# -------------
#   all testbed devices are described here

devices:

    <name>: # device name (hostname) goes here. Each device requires its
            # own description section within devices block

        type:   # device type generic string
                # use this to describe the type of device
                #   Eg: ASR9k
                # (required)

         connections:
            # block describing the 'ways', 'methods' and 'paths' of
            # connecting to this device. eg, telnet, ssh, netconf, etc
            # (required)
```

I am by no means a python programmer, but looking at this section of code in learn_genie.py module (https://github.com/clay584/genie_collection/blob/master/clay584/genie/plugins/modules/learn_genie.py):
```
...
    testbed = {
        "devices": {
            host: {
                "ip": host,
                "port": port,
                "protocol": protocol,
                "username": username,
                "password": password,
                "os": os,
            }
        }
    }

    tb = load(testbed)
```
it appear that neither "type" nor "connections" are specified/being passed through.

Do you think this could be related to the error I am getting?
Is it a possibility that pyATS team has recently changed testbed file schema (eg. by making "type" and "connections" to be required keys) and this is why it's complaining about "missing keys"?!
